name: "Merge-by"
description: "Tracks the status of ongoing pull requests and provides expected dates for merging"

inputs:
  operation:
    description: 'The operation to run as part of this action (table, bump-dates)'
    required: true
    default: 'build-table'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      shell: bash

    - uses: actions/github-script@v7
      if: ${{ inputs.operation == 'build-table' }}
      with:
        script: |
            const script = require("./merge-by/scripts/build-table-and-notify.js");
            await script({ github, context });

    - uses: actions/github-script@v7
      if: ${{ inputs.operation == 'bump-dates' }}
      with:
        script: |
            const script = require("./merge-by/scripts/bump-dates.js");
            await script({ github, context });

          