name: "Merge-by"
description: "Tracks the status of ongoing pull requests and provides expected dates for merging"

inputs:
  operation:
    description: 'The operation to run as part of this action (build-table, bump-dates)'
    required: true
    default: 'build-table'

runs:
  using: "composite"
  steps:
    - run: mkdir fake-pkg && cd fake-pkg && npm init -y && npm install dayjs
      shell: "sh"
    - uses: actions/github-script@v7
      if: ${{ inputs.operation == 'build-table' }}
      with:
        script: |
            const script = require("${{ github.action_path }}/scripts/build-table-and-notify.js");
            await script({ github, context, require });
    - uses: actions/github-script@v7
      if: ${{ inputs.operation == 'bump-dates' }}
      with:
        script: |
            const script = require("${{ github.action_path }}/scripts/bump-dates.js");
            await script({ github, context });

          