name: "Parse environment variables"
description: "Reading and parsing global environment variables"
runs:
  using: "composite"
  steps:
    - run: |
        cd ${{github.action_path}} 
        # Sanitize envvars by (in order)
        # 1. remove comments (start with #); 
        # 2. remove blank lines
        # 3. quote the whole string with double quotes
        # 4. prefix "echo" and append ">> $GITHUB_ENV" 
        sed '/^#/d' envvars.env | awk NF | sed -e "s/\(.*\)/'\1'/" > envvars.env.one
        awk '{ print "echo",$0,">> $GITHUB_ENV" }' envvars.env.one > envvars.sh
        chmod +x envvars.sh
        ./envvars.sh
      shell: bash