name: "Parse environment variables"
description: "Reading and parsing global environment variables"
runs:
  using: "composite"
  steps:
    - run: |
        cd ${{github.action_path}} 
        # Sanitize envvars by (in order)
        # 1. remove comments (start with #); 
        # 2. remove blank lines
        sed '/^#/d' envvars.env | awk NF > envvars.env.new
        rm envvars.env
        mv envvars.env.new envvars.env
        cat envvars.env >> $GITHUB_ENV

        # Default branches pulled from json file
        echo 'DEFAULT_BRANCHES_JSON_TEXT<<EOF' >> $GITHUB_ENV
        cat defaultBranches.json >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      
      shell: bash