name: "Jfrog Download"
description: "Download artifacts from jfrog"
inputs:
  manifest-file-path:
    description: 'the location of the manifest file'
    required: false
  source-path-or-pattern:
    description: 'the download source path of pattern (remote)'
    required: false
  default-target-path:
    description: 'the default download target path (local). Can be overwritten by "target" property in any package in manifest file'
    required: true
  extra-options:
    description: 'jfrog rt command extra options'
    required: false
  default-repository:
    description: 'the default repository. Usually either libs-snapshot-local or libs-release-local'
    required: false
  expected-count:
    description: 'the expected number of downloaded artifacts'
    required: false
  bypass-validation:
    description: 'if the source on artifactory does not exist - expected, we shall bypass the validation check'
    required: false
  
runs:
  using: 'node12'
  main: 'dist/index.js'