name: "Generic Setup"
description: "Generic setup for all project builds"
inputs:
  manifest:
    description: Custom manifest file to overwrite default manifest exists in project
    required: false
  extra-init:
    description: Extra initialization code to run (javascript)
    required: false
outputs:
  package-info-json-text:
    description: 'Parsed manifest information to a json string'

runs:
  using: 'node12'
  main: 'dist/index.js'