name: "Publish"
description: "Publish to artifactory for all project builds"
inputs:
  artifacts:
    description: 'artifacts to upload, also support multiple line inputs'
    required: false
  perform-release:
    description: 'flag to perform steps to release'
    required: false
    default: 'false'
  sigstore-sign-artifacts:
    description: 'use cosign to sign the artifacts as blobs'
    required: false
    default: 'false'
  pre-release-string:
    description: 'pre-release string'
    required: false
  publish-target-path-pattern:
    description: path format for publishing to artifactory
    required: false
    default: '{repository}/{package}{subproject}/{version}{branchtag-uc}/'
  publish-target-file-pattern:
    description: format for the file name published to artifactory
    required: false
    default: '{filename}-{publishversion}{fileext}'
  skip-upload:
    description: not doing an skip-upload
    required: false
    default: 'false'
    
runs:
  using: 'composite'
  steps: 
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.3.0
      if: ${{ inputs.sigstore-sign-artifacts == 'true' }} 
    - name: setup node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16
    - name: Debug Info-BASH
      run: ls -lask ${GITHUB_ACTION_PATH}
      shell: bash
    - name: Debug Info-SH
      run: ls -lask ${GITHUB_ACTION_PATH}
      shell: sh
    - name: Run publish
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUTS: ${{ toJSON(inputs) }}