name: "Publish"
description: "Publish to artifactory for all project builds"
inputs:
  artifacts:
    description: 'artifacts to upload, also support multiple line inputs'
    required: false
  perform-release:
    description: 'flag to perform steps to release'
    required: false
    default: 'false'
  pre-release-string:
    description: 'pre-release string'
    required: false
  publish-target-path-pattern:
    description: path format for publishing to artifactory
    required: false
    default: '{repository}/{package}{subproject}/{version}{branchtag-uc}/'
  publish-target-file-pattern:
    description: format for the file name published to artifactory
    required: false
    default: '{filename}-{publishversion}{fileext}'
  skip-upload:
    description: not doing an skip-upload
    required: false
    default: 'false'

outputs:
  zowe-pax-jfrog-upload-target:
    description: zowe pax jfrog upload target
    
runs:
  using: 'node12'
  main: 'dist/index.js'
