name: "Release"
description: "Release the component if PERFORM_RELEASE is checked"
inputs:
  github-tag-prefix:
    description: 'tag prefix'
    required: false
  generic-bump-version:
    description: 'flag to indicate if doing a generic version bump'
    default: 'false'
    required: false


runs:
  using: 'node20'
  main: 'dist/index.js'

