name: "Check permission"
description: "Permission check for current github actor to see if it has write access"
inputs:
  github-token:
    description: 'github token for authenticating api requests'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
