name: "Check permission"
description: "Permission check for current github actor to see if it has write access"
inputs:
  github-token:
    description: 'github token for authenticating api requests'
    required: true
outputs:
  user-permission:
    description: 'return the user permission'

runs:
  using: 'node20'
  main: 'dist/index.js'
